### ISSUE TITLE
adsr hold calculation incorrect?

### ISSUE THREAD

**Issue by esp1** [ctford/cljs-bach#4]
In the adsr function, the remainder for the hold is calculated by subtracting the attack, decay, and sustain from the duration. I think this should be attack, decay, and **release** instead, as those are the adsr time parameters, and sustain is a level parameter.

https://github.com/ctford/cljs-bach/blob/master/src/cljs_bach/synthesis.cljs#L92

**Comment by ctford** [comment]
Hmm, you're right, that does look wrong.
